---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Create molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        privileged: "{{ item.privileged | default(omit) }}"
        state: started
      loop: "{{ molecule_yml.platforms }}"