---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python and required packages
      raw: |
        apt-get update
        apt-get install -y python3 python3-apt
      changed_when: false

    - name: Gather facts
      setup:

    - name: Install required packages
      apt:
        name: 
          - sudo
          - bash
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'