---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install system tools
  apt:
    name:
      - htop
      - atop
      - btop
      - mc
    state: present
  when: ansible_os_family == 'Debian'