---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu1804-ansible"
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    capabilities:
      - SYS_ADMIN

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    v: 1

verifier:
  name: ansible
  options:
    v: 1

scenario:
  name: default
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
