---
# https://computingforgeeks.com/install-prometheus-server-on-centos-rhel/
- hosts: hp
  become: yes
  remote_user: root
  become_user: root
  
  roles:
    - install_server
    - configure_server
    - install_node_exporter
  
