---
- hosts: hp
  become: yes
  remote_user: root
    #  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest

        #  - name: Install java
        #yum:
        #name: java-11-openjdk-devel
        #state: present
  - name: Install unzip
    yum:
      name: unzip
      state: latest
  - name: Unarchive AWS-CLI
    ansible.builtin.unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp/
      remote_src: yes
  - name: Install AWS-CLI
    ansible.builtin.command:
      cmd: /tmp/aws/install --update
 
  - name: Show AWS-CLI version
    shell: aws --version
    register: comand_output
  - debug:
      var: comand_output.stdout_lines
