version: '2'
services:
  ansible:
    container_name: ansible-master
    image: ansible_v2
    # command: ifconfig
    tty: true
    ports:
      - '3000:22'
    volumes:
      - C:/Dropbox/Git/devops-lab/k8s-lab/ansible:/ansible
    networks:
      asus:
        ipv4_address: 192.168.2.99
networks:
  asus:
    # external: true
    name: asus
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.1.1