Vagrant.configure("2") do |config|
	config.vm.define "k8s-master-01" do |k8s_master|
		k8s_master.vm.box = "generic/ubuntu2004"
        k8s_master.vm.network "public_network", bridge: "ASUS USB-AC53 Nano USB Wireless adapter", ip: "192.168.1.100"
        k8s_master.vm.hostname = "k8s-master"
	end

	config.vm.define "k8s-worker-01" do |k8s_worker|
		k8s_worker.vm.box = "generic/ubuntu2004"
        k8s_worker.vm.network "public_network", bridge: "ASUS USB-AC53 Nano USB Wireless adapter", ip: "192.168.1.101"
        k8s_worker.vm.hostname = "k8s-worker-01"

	end
end