apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-ingress
  namespace: portainer
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`portainer.yourdomain.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: portainer
      port: 9000
