# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "ubuntu-vagrant-01" do |subconfig|
        subconfig.vm.box = "ubuntu/jammy64"
        subconfig.vm.hostname = "ubuntu-vagrant-01"
        # subconfig.vm.provider "virtualbox" do |vb|
        #     vb.customize ["modifyvm", :id, "--nic1", "none"]
        # end

        subconfig.vm.network "public_network", bridge: "eno1", ip: "192.168.0.140", auto_config: true
        # , :adapter => 1
        subconfig.vm.box_check_update = false
        subconfig.vm.provider "virtualbox" do |h|
            # h.enable_virtualization_extensions = false
            h.linked_clone = false
        #    h.vmname = "ubuntu_cluster_master"
            h.name = "Ubuntu-22.04-VirtualBox"
            h.gui = false
            h.memory = "1024"
            h.cpus = 1
        end
        subconfig.vm.provision "shell", inline: <<-SHELL
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
        SHELL
        # subconfig.vm.provision "ansible" do |a|
        #     a.verbose = "v"
        #     a.playbook = "master_playbook.yaml"
        # end
    end
end


# Optional: Provisioning script to set DNS server
# config.vm.provision "shell", inline: <<-SHELL
# echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
# SHELL
  # Disable default NAT
#   config.vm.provider "virtualbox" do |vb|
#     vb.customize ["modifyvm", :id, "--nic1", "none"]
#   end

# Vagrant.configure("2") do |config|
#     config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS codename is Jammy Jellyfish
#     config.vm.box_check_update = false
  
#     config.vm.provider "virtualbox" do |vb|
#       vb.name = "Ubuntu-22.04-VirtualBox"
#       vb.gui = false
#       vb.memory = "1024"
#       vb.cpus = 2
#     end
  
    # Optional: If you want to run a script on the VM after booting up
    # config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL
#   end
  
