---
- name: Configure Zsh Extended History for regular users
  lineinfile:
    path: "/home/{{ item.1 }}/.zshrc"
    line: "{{ item.0 }}"
    create: yes
  loop: "{{ options | product(zsh_users) | list }}"
  when: item.1 != 'root' and ansible_os_family == 'RedHat'
  loop_control:
    label: "{{ item.1 }}"
  vars:
    options:
      - 'setopt EXTENDED_HISTORY'
      - 'setopt HIST_SAVE_NO_DUPS'
      - 'setopt HIST_EXPIRE_DUPS_FIRST'
      - 'setopt HIST_VERIFY'
      - 'setopt HIST_IGNORE_SPACE'
      - 'setopt SHARE_HISTORY'

- name: Configure Zsh Extended History for root user
  lineinfile:
    path: "/root/.zshrc"
    line: "{{ item }}"
    create: yes
  loop: "{{ options }}"
  when: "'root' in zsh_users and ansible_os_family == 'RedHat'"
  vars:
    options:
      - 'setopt EXTENDED_HISTORY'
      - 'setopt HIST_SAVE_NO_DUPS'
      - 'setopt HIST_EXPIRE_DUPS_FIRST'
      - 'setopt HIST_VERIFY'
      - 'setopt HIST_IGNORE_SPACE'
      - 'setopt SHARE_HISTORY'
